spring:
  application:
    name: COURSE-CLOUD-GATEWAY
  config:
    import: configserver:http://${confighost}:${configport}
    
    
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761
    

  
  
